#!/bin/sh
# Prints the battery level when under >20%

battery_level=`acpi -b | grep -Po '[0-9]+(?=%)' | awk '{ sum += $1 }; END {print sum}'`
if [ $battery_level -le 20 ]
then
	notify-send -t 5000 -u critical "BATTERY LOW" "$battery_level% remaining."
elif [ $battery_level -ge 85 ]
then
	notify-send -t 5000 -u low "BATTERY FULLY CHARGED" "You should unplug now."
fi
