#!/bin/sh
# Uses an appropriate program to open a link depending of its MIME type. Basically Luke Smith's linkhandler, with a few modifications.
# Mostly used for IRC

if [ -z "$1" ]; then
	url="$(xclip -o)"
else
	url="$1"
fi

if echo "$url" | grep -E '.*mkv?.*|.*webm?.*|.*gif?.*|.*mp4?.*|.*youtube\.com/watch.*|.*youtube\.com/playlist.*|.*youtube\.com/shorts.*|.*youtu\.be.*|.*odysee\.com.*|.*twitch\.tv.*'; then
		setsid -f mpv -quiet "$url" >/dev/null 2>&1 
  elif echo "$url" | grep -E '.*png?.*|.*jpg?.*|.*jpeg?.*|.*webp?.*'; then
		curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && feh "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 &
  elif echo "$url" | grep -E '.*pdf?.*|.*cbz?.*|.*cbr?.*|.*epub?.*|.*mobi?.*'; then
		curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && zathura "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 &
  elif echo "$url" | grep -E '.*mp3?.*|.*aac?.*|.*opus?.*|.*flac?.*'; then
		setsid -f mpv "$url" >/dev/null 2>&1
  else
    setsid -f "$BROWSER" "$url" >/dev/null 2>&1
fi
