#!/bin/sh
# Play all the URLs found on a playlist file using mpv + yt-dlp.

PLAYLIST=$HOME/.playlist
if [ -z "$(cat $PLAYLIST)" ];
then
  dunstify -t 2000 -u critical "PLAYLIST IS EMPTY" 
else
  for url in $(cat $PLAYLIST)
  do
    mpv $url
    if [ $? -ne 0 ]; then
      dunstify -t 2000 -u critical "ERROR" " Failed to read $url"
    fi
      sed -i "\|$url|d" $PLAYLIST
  done
fi


