#!/bin/sh
# Play all the URLs found on a playlist file using mpv + yt-dlp.

PLAYLIST=$HOME/.playlist
if [ -z "$(cat "$PLAYLIST")" ];
then
	notify-send -t 2000 -u critical "PLAYLIST IS EMPTY" 
else
	SIZE="$(wc -l < "$PLAYLIST")"
	VIDEOCOUNT=1
  while IFS="" read -r url || [ -n "$url" ]
	do
		ACTION=$(dunstify -u normal -t 3000 --action="default, killPlaylist" "$VIDEOCOUNT/$SIZE" "Middle-click to stop the playlist")
		case "$ACTION" in
			"default")
        pkill playlist
				;;
		esac
    VIDEOCOUNT=$((VIDEOCOUNT+1))
		if ! mpv "$url"; then
			notify-send -t 2000 -u critical "ERROR" "Failed to read $url"
		fi
	done < "$PLAYLIST"
  sed -i "1,$VIDEOCOUNT d" "$PLAYLIST"
fi
