#!/bin/bash
# Pomodoro timer using dzen2 notifications

# Timer = (echo Timer; for i in {25..0}; do echo $((i--)) min; sleep 60; done) | dzen2 -bg blue -fg white -fn "Terminus:size=14" -w 100 -h 17 -x 1281 -p 25m
# Keep track of number of pomodoros cycles
# Bigger break after 4 cycles (15 min)

export DISPLAY=':0' 
aplay /home/rosco/Scripts/notification_sound.wav &
(echo | dzen2 -bg blue -p 15 -w '304' -x 808 -y 523 -h 54) |
(sleep 0.05 ; echo "WORK TIME" | dzen2 -bg black -fg blue -p 15 -w '300' -x 810 -y 525 -h 50 -fn "Terminus:size=14") |
(echo Timer; for i in {25..1}; do echo $((i--)) min; sleep 60; done) |
(dzen2 -bg blue -fg white -fn "Terminus:size=14" -w 100 -h 17 -x 1281)
aplay /home/rosco/Scripts/notification_sound.wav & 
(echo | dzen2 -bg magenta -p 15 -w '304' -x 808 -y 523 -h 54) |
(sleep 0.05 ; echo "BREAK TIME" | dzen2 -bg black -fg magenta -p 15 -w '300' -x 810 -y 525 -h 50 -fn "Terminus:size=14") |
(echo Timer; for i in {5..1}; do echo $((i--)) min; sleep 60; done) |
(dzen2 -bg magenta -fg white -fn "Terminus:size=14" -w 100 -h 17 -x 1281)

