#!/bin/sh
#Pomodoro timer switch for dwm

TOGGLE=$HOME/.pomodoro

if [ ! -e $TOGGLE ]; then
  touch $TOGGLE
  (pomodoro &)
else
  rm $TOGGLE
  # Kill the pomodoro process
  notify-send -t 2000 -u critical "Pomodoro exited successfully." -h string:x-dunst-stack-tag:pomodoro
  pkill pomodoro
fi
