#!/bin/bash
#Pomodoro timer switch for dwm

TOGGLE=$HOME/.pomodoro
if [ ! -e $TOGGLE ]; then
# Creating the timer
  touch $TOGGLE
  systemctl --user start pomodoro
else
# Stopping the timer
  rm $TOGGLE
  systemctl --user stop pomodoro
  (echo | dzen2 -bg green -p 3 -w '304' -x 808 -y 523 -h 54) | 
  (sleep 0.05 ; echo "Pomodoro exited successfully." | dzen2 -bg black -fg green -p 3 -w '300' -x 810 -y 525 -h 50 -fn Terminus)
fi

