#!/bin/sh
# Prompts the user for a region of the screen and a duration, and records the screen.
# Requires ffmpeg, slop and dmenu

SCREEN_SIZE=$(slop -D -f '-video_size %wx%h -i :0.0+%x,%y')
DURATION=$(dmenu -p "Duration (in seconds):" < /dev/null)
VIDEO_DIR="/home/rosco/video/recordings"
FILENAME="recording_$(date +%s).webm"
echo "$FILENAME"

ffmpeg -f x11grab "$SCREEN_SIZE" -framerate 25 -t "$DURATION" -c:v libvpx-vp9 -b:v 0 -crf 35 -deadline realtime -cpu-used 8 "$VIDEO_DIR"/"$FILENAME"
