#!/bin/sh
# Prompts the user for a region of the screen and a duration, and records the screen.
# Requires ffmpeg, slop and dmenu

REGION=$(slop -D -f '%w,%h,%x,%y')
WIDTH=$(echo "$REGION" | cut -d, -f1)
HEIGHT=$(echo "$REGION" | cut -d, -f2)
X=$(echo "$REGION" | cut -d, -f3)
Y=$(echo "$REGION" | cut -d, -f4)
REGION_SIZE='-video_size '"$WIDTH"'x'"$HEIGHT"''
INPUT='-i :0.0+'"$X"','"$Y"''
DURATION=$(dmenu -p "Duration (in seconds):" < /dev/null)
VIDEO_DIR="/home/rosco/video/recordings"
FILENAME="recording_$(date +%s).webm"

COMMAND='ffmpeg -f x11grab '"$REGION_SIZE"' '"$INPUT"' -framerate 25 -t '"$DURATION"' -c:v libvpx-vp9 -b:v 0 -crf 35 -deadline realtime -cpu-used 8 '"$VIDEO_DIR"'/'"$FILENAME"''

eval "$COMMAND"
#ffmpeg -f x11grab -video_size 175x153 -grab_x 175 -grab_y 457 -i :0.0 -framerate 25 -t 2 -c:v libvpx-vp9 -b:v 0 -crf 35 -deadline realtime -cpu-used 8 ~/downloads/test.mp4

 

