#!/bin/sh
# Rsyncs my home directory with my external storage.

echo "Starting sync.."
echo "Synchronizing audio.."
sudo rsync -r --progress --ignore-existing $HOME/audio/albums/* /mnt/storage/music

echo "Synchronizing files.."
sudo rsync -r --progress --ignore-existing $HOME/files/bank/* /mnt/storage/files/documents/bank
sudo rsync -r --progress --ignore-existing $HOME/files/medical/* /mnt/storage/files/documents/medical
sudo rsync -r --progress --ignore-existing $HOME/files/school/* /mnt/storage/files/documents/school
sudo rsync -r --progress --ignore-existing $HOME/files/identity/* /mnt/storage/files/documents/identity
sudo rsync -r --progress --ignore-existing $HOME/files/visa/* /mnt/storage/files/documents/visa
sudo rsync -r --progress --ignore-existing $HOME/files/docs/* /mnt/storage/files/documents/docs
sudo rsync -r --progress --ignore-existing $HOME/files/invoices/* /mnt/storage/files/documents/invoices
sudo rsync -r --progress --ignore-existing $HOME/files/notes/* /mnt/storage/files/documents/notes
sudo rsync -r --progress --ignore-existing $HOME/files/books/* /mnt/storage/books

echo "Synchronizing pictures.."
sudo rsync -r --progress --ignore-existing $HOME/pictures/photos /mnt/storage/pictures

echo "Synchronizing video.."
sudo rsync -r --progress --ignore-existing $HOME/video/movies/* /mnt/storage/movies
sudo rsync -r --progress --ignore-existing $HOME/video/series/* /mnt/storage/series
sudo rsync -r --progress --ignore-existing $HOME/video/anime/* /mnt/storage/anime
echo "End of sync."
