#!/bin/sh
# Rsyncs my home directory with my external storage.

echo "Mounting device.."
sudo mount /dev/sdb1 /mnt/storage
echo "Starting sync.."

echo "Synchronizing audio.."
sudo rsync -r --progress --ignore-existing $HOME/audio/albums/* /mnt/storage/music

echo "Synchronizing files.."
sudo rsync -r --progress --ignore-existing $HOME/files/admin/* /mnt/storage/files/documents
sudo rsync -r --progress --ignore-existing $HOME/files/books/* /mnt/storage/books

echo "Synchronizing pictures.."
sudo rsync -r --progress --ignore-existing $HOME/pictures/photos /mnt/storage/pictures

echo "Synchronizing video.."
sudo rsync -r --progress --ignore-existing $HOME/video/movies/* /mnt/storage/movies
sudo rsync -r --progress --ignore-existing $HOME/video/series/* /mnt/storage/series
sudo rsync -r --progress --ignore-existing $HOME/video/anime/* /mnt/storage/anime

echo "End of sync."
