#!/bin/sh
# Checks if a magnet exists in the clipboard and adds it to transmission-remote

SELECTION="$(xclip -o -selection clipboard)"
PRIMARY="$(xclip -o)"
if transmission-remote -a $1;
then
	notify-send -t 2000 -u normal "TORRENT SUCCESSFULLY ADDED" 
elif transmission-remote -a $SELECTION;
then
	notify-send -t 2000 -u normal "TORRENT SUCCESSFULLY ADDED" "$URL"
elif transmission-remote -a  $PRIMARY;
then
	notify-send -t 2000 -u normal "TORRENT SUCCESSFULLY ADDED" "$URL"
else
	notify-send -t 2000 -u critical "ERROR" "No magnet links found"
fi
