#!/bin/bash
#Toggles the touchpad

TOGGLE=$HOME/.touchpad
if [ ! -e $TOGGLE ]; then
  touch $TOGGLE
  xinput disable "SynPS/2 Synaptics TouchPad"
  dunstify -u low -t 2000 "TOUCHPAD DISABLED"
else
  rm $TOGGLE
  xinput enable "SynPS/2 Synaptics TouchPad"
  dunstify -u low -t 2000 "TOUCHPAD ENABLED"
fi


