#!/bin/sh
# Increments the volume by 5% and sends a notification.

pactl set-sink-volume @DEFAULT_SINK@ +5%
NEW_VOLUME=$(pactl list sinks | grep -oP "Volume: .*?%" | awk '{print $5}')
notify-send -u low -t 1000 "VOLUME" "$NEW_VOLUME" -h string:x-dunst-stack-tag:volume
