#!/bin/sh

toggle(){
  # check if vpn is an active connection
  if nmcli con show --active | grep -q "vpn"; then
    nmcli con down vpn > /dev/null && notify-send -u normal -t 2000 "VPN is off"
  else
    nmcli con up vpn > /dev/null && notify-send -u normal -t 2000 "VPN is on"
  fi
}

usage(){
printf "vpn [-ht]
-t: toggles the vpn
-h: print this help section" 
}

while getopts 'ht' flag; do
  case "${flag}" in
    t) toggle ;;
    h) usage ;;
  esac
done

