#!/bin/sh

toggle(){
  if nmcli con show --active | grep -q "vpn"; then
    if nmcli con down vpn > /dev/null; then
      notify-send -u low -t 2000 "VPN is off"
    else
      notify-send -u critical -t 2000 "ERROR: VPN could not be turned off"
    fi
  else
    if nmcli con up vpn > /dev/null; then
      notify-send -u low -t 2000 "VPN is on"
    else
      notify-send -u critical -t 2000 "ERROR: VPN could not be turned on"
    fi
  fi
}

usage(){
printf "vpn [-ht]
-t: toggles the vpn
-h: print this help section" 
}

while getopts 'ht' flag; do
  case "${flag}" in
    t) toggle ;;
    h) usage ;;
  esac
done

