#!/bin/sh
# Sends notifications when there's a calcurse appointment in the near future.

DAILY_PLANNING="$(calcurse --filter-type apt,recur-apt,event,recur-event --format-apt "%m in %(remaining: %H hours, %M minutes) \n" --format-recur-apt "%m in %(remaining: %H hours, %M minutes) \n" --format-event "%m \n" --format-recur-event "%m \n" -Q --days 1 | awk -e '$0 !~ /[0-9]{2}\/[0-9]{2}\/[0-9]{2}:/ {print $0}' | awk -e '$0 !~ /-[0-9]+/ {print $0}')"
WEEK_PLANNING="$(calcurse --filter-type event,recur-event,apt,recur-apt --output-datefmt "<b>%A</b>" --format-event " %m \n" --format-recur-event " %m \n"  --format-apt " %m (%S ➜ %E) \n" --format-recur-apt " %m (%S ➜ %E) \n" -Q --from tomorrow --days 5 | sed "s/$(date --date=tomorrow +%A)/Tomorrow/g; /^$/d")"
TO_DO_ITEMS="$(calcurse -t --format-todo "<b>[%p]</b> - %m\n" | awk 'NR!=1 {print $0}')"

# Print out events and appointments in order

if [[ -n $DAILY_PLANNING ]]; then	
	notify-send -u normal -t 20000 "TODAY" "$DAILY_PLANNING"
fi

if [[ -n $WEEK_PLANNING ]]; then
	notify-send -u normal -t 20000 "NEXT 5 DAYS" "$WEEK_PLANNING"
fi

if [[ -n $TO_DO_ITEMS ]]; then
	notify-send -u normal -t 20000 "TO-DO LIST" "$TO_DO_ITEMS"
fi
