#!/bin/sh
# Sends notifications when there's a calcurse appointment in the near future.

DAILY_APPOINTMENTS="$(calcurse --filter-type apt,recur-apt --format-apt "%m in %(remaining: %H hours, %M minutes)" --format-recur-apt "%m in %(remaining: %H hours, %M minutes)" -Q --days 1 | awk -e '$1 !~ /[0-9]{2}\/[0-9]{2}\/[0-9]{2}:/ {print $0}')"
WEEK_APPOINTMENTS="$(calcurse --filter-type apt,recur-apt --format-apt "%m in %(remaining:%d days, %H hours, %M minutes)" --format-recur-apt "%m in %(remaining:%d days, %H hours, %M minutes)" -Q --from tomorrow --days 7 | awk -e '$1 !~ /[0-9]{2}\/[0-9]{2}\/[0-9]{2}:/ {print $0}')"
DAILY_EVENT="$(calcurse --filter-type event,recur-event --format-event "%m" --format-recur-event "%m)" -Q --days 1 | awk -e '$1 !~ /[0-9]{2}\/[0-9]{2}\/[0-9]{2}:/ {print $0}')"
WEEK_EVENT="$(calcurse --filter-type event,recur-event --format-event "%m" --format-recur-event "%m" -Q --from tomorrow --days 7)"

if [[ -n $DAILY_APPOINTMENTS || -n $DAILY_EVENT ]]; then
	notify-send -u normal -h string:fgcolor:#00ffff -h string:frcolor:#00ffff -t 20000 "TODAY" "$DAILY_EVENT $DAILY_APPOINTMENTS"
fi 

if [[ -n $WEEK_APPOINTMENTS ]]; then
	notify-send -u normal -h string:fgcolor:#ff7518 -h string:frcolor:#ff7518 -t 20000 "NEXT 7 DAYS" "$WEEK_APPOINTMENTS"
fi
