#!/bin/sh
#Opens a link copied into any clipboard with the appropriate program for its MIME type. Requires curl.

# List of programs used
# ---------------------
# VIDEO = mpv
# AUDIO = mpv
# IMAGE = feh
# PDF = zathura
# TEXT = nvim

URL_REGEX='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

if [[ -z "$(xclip -o -sel clip)" || ! "$(xclip -o -sel clip)" =~ $URL_REGEX ]]
then
	if [[ -z "$(xclip -o)" || ! "$(xclip -o)" =~ $URL_REGEX ]]
	then
		notify-send -t 2000 -u critical "ERROR" "No valid URLs found on clipboard." 
		exit
	else
		URL="$(xclip -o)"
	fi
else
	URL="$(xclip -o -sel clip)"
fi

MIME_TYPE=$(curl -sI $URL | awk -F ' ' '/content-type:/ {print $2}' | sed 's/.$//')

case "$MIME_TYPE" in
	image*)
		feh $URL
		;;
	audio*)
		mpv $URL
		;;
	video*)
		mpv $URL
		;;
	application/pdf)
		zathura $URL
		;;
	*)
		qutebrowser $URL
		;;
esac

if [[ $? != 0 ]]; then
	notify-send -t 2000 -u critical "ERROR" "An error has occured while attempting to open the link."
fi
